image: centos/systemd
before_script:
  - python --version
  - yum install epel-release -y
  - yum install python-pip gcc python-devel -y
  - pip install virtualenv
  - virtualenv ansible
  - source ansible/bin/activate


molecule:
  stage: test
  tags:
    - pip36
    - docker

  script:
    - python --version
    - pip36 install ansible molecule 'docker<3.0'
    - ansible --version
    - molecule --version
    - molecule test 
